---
title: "shot chart-DS"
output: html_document
date: '2022-07-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

install.packages("nbastatR")
devtools::install_github("abresler/nbastatR")
devtools::install_github("lbenz730/ncaahoopR")
install.packages("grImport2")
install.packages("rsvg")

```
#libraries
```{r libraries}

library(tidyverse)
library(nbastatR)
library(ncaahoopR)
library(extrafont)
library(cowplot)
library(ggimage)
library(grImport2)
library(rsvg)

Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)
```

# Creating Court 
```{r creating court}
# Creating court and plotting

circle_points = function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(tibble(x = center[1] + radius * cos(angles),
                    y = center[2] + radius * sin(angles)))
}
# Court Dimenons & lines
width = 50
height = 94 / 2
key_height = 19
inner_key_width = 12
outer_key_width = 16
backboard_width = 6
backboard_offset = 4
neck_length = 0.5
hoop_radius = 0.75
hoop_center_y = backboard_offset + neck_length + hoop_radius
three_point_radius = 23.75
three_point_side_radius = 22
three_point_side_height = 14
# Court themes
court_themes = list(
  light = list(
    court = 'floralwhite',
    lines = '#999999',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = "#000000"
  ),
  dark = list(
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "#000000"
  ),
  ppt = list(
    court = 'gray20',
    lines = 'white',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray20"
)
)
# Function to create court based on given dimensions
plot_court = function(court_theme = court_themes$light, use_short_three = FALSE) {
  if (use_short_three) {
    three_point_radius = 22
    three_point_side_height = 0
  }
  
  court_points = tibble(
    x = c(width / 2, width / 2, -width / 2, -width / 2, width / 2),
    y = c(height, 0, 0, height, height),
    desc = "perimeter"
  )
  
  court_points = bind_rows(court_points , tibble(
    x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
    y = c(0, key_height, key_height, 0),
    desc = "outer_key"
  ))
  
  court_points = bind_rows(court_points , tibble(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset, backboard_offset),
    desc = "backboard"
  ))
  
  court_points = bind_rows(court_points , tibble(
    x = c(0, 0), y = c(backboard_offset, backboard_offset + neck_length), desc = "neck"
  ))
  
  foul_circle = circle_points(center = c(0, key_height), radius = inner_key_width / 2)
  
  foul_circle_top = filter(foul_circle, y > key_height) %>%
    mutate(desc = "foul_circle_top")
  
  foul_circle_bottom = filter(foul_circle, y < key_height) %>%
    mutate(
      angle = atan((y - key_height) / x) * 180 / pi,
      angle_group = floor((angle - 5.625) / 11.25),
      desc = paste0("foul_circle_bottom_", angle_group)
    ) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x, y, desc)
  
  hoop = circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "hoop")
  
  restricted = circle_points(center = c(0, hoop_center_y), radius = 4) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "restricted")
  
  three_point_circle = circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line = tibble(
    x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
    y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
    desc = "three_point_line"
  )
  
  court_points = bind_rows(
    court_points,
    foul_circle_top,
    foul_circle_bottom,
    hoop,
    restricted,
    three_point_line
  )
  
  
  court_points <- court_points
  
  # Final plot creation
  ggplot() +
    geom_path(
      data = court_points,
      aes(x = x, y = y, group = desc),
      color = court_theme$lines
    ) +
    coord_fixed(ylim = c(0, 45), xlim = c(-25, 25)) +
    theme_minimal(base_size = 22) +
    theme(
      text = element_text(color = court_theme$text),
      plot.background = element_rect(fill = 'gray20', color = 'gray20'),
      panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      legend.background = element_rect(fill = court_theme$court, color = court_theme$court),
      legend.margin = margin(-1, 0, 0, 0, unit = "lines"),
      legend.position = "bottom",
      legend.key = element_blank(),
      legend.text = element_text(size = rel(1.0))
    )
}
```

# NBA Data, and Durant
```{r}
# Grab team names to type into teams_shots function
nba_teams() %>% filter(isNonNBATeam == 0)

# Grab team shot data
nets_ply <- teams_shots(teams = "Brooklyn Nets", 
                    seasons = 2021,
                    season_types = "Playoffs"
                    )

#make season type variable
nets_reg <- nets_reg %>% mutate(season = "Regular")
nets_ply <- nets_ply %>% mutate(season = "Playoffs")

#combine into one dataframe
nets <- rbind(nets_reg, nets_ply)

#for all teams 2021 season
shots21 <- teams_shots(seasons = 2021, season_types = "Regular Season", all_active_teams = TRUE)

shots21 <- shots21 %>% 
  mutate(x = as.numeric(as.character(locationX)) / 10, 
         y = as.numeric(as.character(locationY)) / 10 + hoop_center_y)

# Horizontally flip the data
shots21$x <- shots21$x * -1 

shots21 %>% ggplot(aes(x = locationX, y = locationY )) + geom_hex()

shots21 %>% ggplot(aes(x = locationX, y = locationY )) + geom_hex() + facet_wrap(~ nameTeam)

#get players with more than 1000 shots
ov1000 <- shots21 %>% group_by(idPlayer) %>% 
  filter(n() > 1000)

#how 'bout just over 100 shots
ov_100 <- shots21 %>% group_by(idPlayer) %>% 
  filter(n() > 100)


# Filter shot data for player & clean data to fit court dimensions
durant <- nets %>% filter(namePlayer=="Kevin Durant") %>% 
  mutate(x = as.numeric(as.character(locationX)) / 10, 
         y = as.numeric(as.character(locationY)) / 10 + hoop_center_y)
# Horizontally flip the data
durant$x <- durant$x * -1 
# Filter shots by game date - this was the most 3's made that season
final_durant <- durant %>% filter(dateGame == 20210615)

#look at left vs right side of court shots
durant <- durant %>% mutate(shot_side = 
                              ifelse(x < 0, "right", "left"))

```

# NBA Chart - Durant one game
```{r}
p1 <- plot_court(court_themes$ppt, use_short_three = F) +
  geom_point(data = final_durant, 
             aes(x = x, y = y, 
                 color = isShotMade, fill = isShotMade
                 ), 
             size =3, shape = 21, stroke = .5
             ) +  
  scale_color_manual(values = c("green4","red3"), 
                     aesthetics = "color", 
                     breaks=c("TRUE", "FALSE"), 
                     labels=c("Made", "Missed")
                     ) +
  scale_fill_manual(values = c("green2","gray20"), 
                    aesthetics = "fill", 
                    breaks=c("TRUE", "FALSE"), 
                    labels=c("Made", "Missed")
                    ) +
  scale_x_continuous(limits = c(-27.5, 27.5)
                     ) +
  scale_y_continuous(limits = c(0, 45)
                     ) +
  theme(plot.title = element_text(hjust = .5, size = 22, 
                                  face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, 
                                     face = "bold", vjust = -8),
        legend.position = c(.5, .85),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, 
                                   face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, 
                                    face = "bold", 
                                    colour = "lightgrey", 
                                    vjust = 8)
        ) +
  ggtitle(label = "Kevin Durant vs. Milwaukee",
          subtitle = "49 PTS | 17 REB | 10 AST | 4-9 3PT - 6/15/21") +
  labs(caption = "Tutorial: @DSamangy")


ggdraw(p1) + 
  theme(plot.background = element_rect(fill="gray20", color = NA)) 

#ggsave("Durant.png", height = 6, width = 6, dpi = 300)
```

#Durant - full season - other players too
```{r}
psc <- plot_court(court_themes$ppt, use_short_three = F) +
  geom_point(data = filter(shots21, namePlayer == "Stephen Curry"), 
             aes(x = x, y = y, 
                 color = isShotMade, fill = isShotMade
                 ), 
             size =3, shape = 21, stroke = .5
             ) +  
  scale_color_manual(values = c("green4","red3"), 
                     aesthetics = "color", 
                     breaks=c("TRUE", "FALSE"), 
                     labels=c("Made", "Missed")
                     ) +
  scale_fill_manual(values = c("green2","gray20"), 
                    aesthetics = "fill", 
                    breaks=c("TRUE", "FALSE"), 
                    labels=c("Made", "Missed")
                    ) +
  scale_x_continuous(limits = c(-27.5, 27.5)
                     ) +
  scale_y_continuous(limits = c(0, 45)
                     ) +
  theme(plot.title = element_text(hjust = .5, size = 22, 
                                  face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, 
                                     face = "bold", vjust = -8),
        legend.position = c(.5, .90),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, 
                                   face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, 
                                    face = "bold", 
                                    colour = "lightgrey", 
                                    vjust = 8)
        ) +
  ggtitle(label = "Steph Curry 2021 Season",
          subtitle = "32 PTS | 5.5 REB | 5.8 AST | 42.1% 3PT") +
  labs(caption = "@jmeerse")

psc
 
ggdraw(psc) + 
  theme(plot.background = element_rect(fill="gray20", color = NA)) 

ggsave("Steph2021.png", height = 6, width = 6, dpi = 300)


#here we can just filter to a certain player
p10 <- plot_court(court_themes$ppt, use_short_three = F) +
  geom_point(data = filter(shots21, namePlayer == "Draymond Green"), 
             aes(x = x, y = y, 
                 color = isShotMade, fill = isShotMade
                 ), 
             size = 3, shape = 21, stroke = .5
             ) +  
  scale_color_manual(values = c("green4","red3"), 
                     aesthetics = "color", 
                     breaks=c("TRUE", "FALSE"), 
                     labels=c("Made", "Missed")
                     ) +
  scale_fill_manual(values = c("green2","gray20"), 
                    aesthetics = "fill", 
                    breaks=c("TRUE", "FALSE"), 
                    labels=c("Made", "Missed")
                    ) +
  scale_x_continuous(limits = c(-27.5, 27.5)
                     ) +
  scale_y_continuous(limits = c(0, 45)
                     ) #+
  #facet_wrap(~shots21$nameTeam)
  
p10


#attach this back onto above for labels
  theme(plot.title = element_text(hjust = .5, size = 22, 
                                  face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, 
                                     face = "bold", vjust = -8),
        legend.position = c(.5, .90),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, 
                                   face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, 
                                    face = "bold", 
                                    colour = "lightgrey", 
                                    vjust = 8)
        ) +
  ggtitle(label = "Kevin Durant 2021 Season",
          subtitle = "29.9 PTS | 7.4 REB | 6.4 AST | 38.3% 3PT") +
  labs(caption = "@jmeerse")

```

#Durant - left vs right
```{r}
#bar chart
durant %>% ggplot(aes(x = shot_side, group = isShotMade, fill = isShotMade)) + geom_bar(position = "dodge")

#proportions
d_shots <- table(durant$shot_side)
d_shot_table <- table(durant$shot_side, durant$isShotMade)
prop.table(d_shot_table, margin = 1)

#scatterplot
p3 <- plot_court(court_themes$ppt, use_short_three = F) +
  geom_point(data = durant, 
             aes(x = x, y = y, 
                 color = side, fill = isShotMade
                 ), 
             size =3, shape = 21, stroke = .5
             ) +  
  scale_color_manual(values = c("green4","red3"), 
                     aesthetics = "color", 
                     breaks=c("left", "right"), 
                     labels=c("Right", "Left")
                     ) +
  scale_fill_manual(values = c("green2","gray20"), 
                    aesthetics = "fill", 
                    breaks=c("TRUE", "FALSE"), 
                    labels=c("Made", "Missed")
                    ) +
  scale_x_continuous(limits = c(-27.5, 27.5)
                     ) +
  scale_y_continuous(limits = c(0, 45)
                     ) +
  theme(plot.title = element_text(hjust = .5, size = 22, 
                                  face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, 
                                     face = "bold", vjust = -8),
        legend.position = c(.5, .85),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, 
                                   face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, 
                                    face = "bold", 
                                    colour = "lightgrey", 
                                    vjust = 8)
        ) +
  ggtitle(label = "Kevin Durant Left v Right",
          subtitle = "50.9% from left, n = 110, 51.7% from right, n = 172") +
  labs(caption = "@jmeerse")

p3

```

#team level stuff
```{r}
teampct <- shots21 %>% group_by(idTeam, nameTeam) %>% 
  summarise(pct2 = sum((typeShot == "2PT Field Goal") & (isShotMade == "TRUE")) / sum(typeShot == "2PT Field Goal"), 
            pct3 = sum((typeShot == "3PT Field Goal") & (isShotMade == "TRUE")) / sum(typeShot == "3PT Field Goal"),
            n = n(),
            )

teams <- filter(df_dict_nba_teams, idLeague == 4)
teampct <- left_join(teampct, teams, by = "idTeam")
teampct = subset(teampct, select = -c(nameTeam.y))

#graph of %2 vs %3
teampct %>% ggplot(aes(x = pct2, 
                       y = pct3)
                   ) + 
  geom_image(aes(image = urlThumbnailTeam), 
             size = .075) +
  geom_text(label = teampct$slugTeam, 
            nudge_y = -.0025, 
            size = 2)


#left vs right side of court
shots21 <- shots21 %>% mutate(shot_side = 
                              ifelse(x < 0, "left", "right"))


shots21 %>% ggplot(aes(x = shot_side, group = isShotMade, fill = isShotMade)) + geom_bar(position = "dodge")

ov1000 %>% ggplot(aes(x = shot_side, group = isShotMade, fill = isShotMade)) + geom_bar(position = "dodge") + facet_wrap(~ namePlayer)

#player sides df
playerside_100 <- ov_100 %>% 
  group_by(idPlayer, namePlayer) %>% 
  summarise(pctlft = sum((shot_side == "left") & (isShotMade == "TRUE")) / sum(shot_side == "left"), 
            pctrt = sum((shot_side == "right") & (isShotMade == "TRUE")) / sum(shot_side == "right"),
            n = n(),
            diff_side = pctrt - pctlft
            ) 

#playerside graph
playerside_100 %>% ggplot(aes(x = pctlft, 
                          y = pctrt, size = n)) + 
  geom_point() + 
  geom_abline(intercept = 0, slope = 1) +
  geom_smooth(method = 'lm') +
  geom_smooth(data = filter(playerside_100, n > 1000), method = 'lm')

#diff_side graph
playerside_100 %>% ggplot(aes(x = diff_side)) + geom_histogram()

```

